# .github/workflows/build-spec.yml

name: Build and Validate CAMARA OpenAPI Spec

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build Master OpenAPI Spec
        run: npm run build

      # --- DEBUGGING STEP ADDED ---
      # This will show us all the files in the directory after the build.
      - name: Verify file creation
        run: ls -R

      - name: Validate OpenAPI Spec
        run: npx @redocly/cli lint --config .redocly.yaml

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(openapi): Regenerate complete CAMARA spec"
          file_pattern: "dist/camara-openapi.yaml"
          commit_user_name: "CAMARA Bot"
          commit_user_email: "camara-bot@users.noreply.github.com"
